from sqlalchemy import (
    Boolean,
    ForeignKey,
    Integer,
    String,
    create_engine
)

from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship
)


DATABASE_URL = "sqlite:///./day40.db"

engine = create_engine(DATABASE_URL)


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    email: Mapped[str] = mapped_column(
        String(150),
        nullable=False
    )

    tasks: Mapped[list["Task"]] = relationship(
        back_populates="user"
    )


class Task(Base):
    __tablename__ = "tasks"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    title: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    completed: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False
    )

    priority: Mapped[int] = mapped_column(
        Integer,
        default=3,
        nullable=False
    )

    description: Mapped[str | None] = mapped_column(
    String(500),
    nullable=True
)

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id"),
        nullable=False
    )

    user: Mapped["User"] = relationship(
        back_populates="tasks"
    )


# 1. What problem do database migrations solve?
# Database migrations allow us to change an existing database schema
# over time without deleting and recreating the entire database.
# They can add, remove, or modify tables, columns, indexes, and
# constraints while preserving existing data where possible.


# 2. Why is Base.metadata.create_all() not enough
#    for production schema evolution?
# create_all() mainly creates tables that do not already exist.
# It does not properly track or manage changes to existing schemas,
# so it is not a replacement for migrations.


# 3. What is Alembic?
# Alembic is a database migration tool commonly used with SQLAlchemy.
# It creates, tracks, applies, and reverses versioned database
# schema changes.


# 4. What is Base.metadata used for by Alembic?
# Base.metadata contains SQLAlchemy's schema information such as
# tables, columns, foreign keys, and constraints.
# Alembic can compare this metadata with the current database schema.


# 5. What does target_metadata = Base.metadata do?
# It gives Alembic access to the SQLAlchemy model metadata so
# autogenerate can compare the ORM schema with the actual database.


# 6. What is the difference between:
#    alembic revision --autogenerate
#    and
#    alembic upgrade head?
#
# revision --autogenerate compares the database schema with
# the SQLAlchemy metadata and generates a migration file.
#
# upgrade head applies the migrations to the actual database
# and moves it to the latest migration version.


# 7. What does upgrade() represent?
# upgrade() contains the operations required to move the
# database schema forward to the newer migration version.


# 8. What does downgrade() represent?
# downgrade() contains the operations required to reverse
# the migration and return the database to the previous version.


# 9. What does "head" mean in Alembic?
# head means the latest migration revision in the current
# Alembic migration chain.


# 10. If I add a new field to my SQLAlchemy model,
#     does that automatically add the column to an
#     existing database? Explain.
# No. Changing the SQLAlchemy model only changes the Python
# model definition. The database must be updated by generating
# a migration and applying it with Alembic.


# 11. Why should generated migrations be inspected
#     before applying them?
# Autogenerated migrations may be incomplete, incorrect, or unsafe.
# They should be reviewed to make sure the generated operations
# match the intended database schema change.


# 12. What does alembic downgrade -1 do?
# It moves the database back by one migration revision by
# running the downgrade() function of the current migration.