from sqlalchemy import (
    Boolean,
    ForeignKey,
    Integer,
    String,
    create_engine,
    Index,
    select,
)

from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
    Session,
)


DATABASE_URL = "sqlite:///./day40.db"

engine = create_engine(DATABASE_URL)


# ============================================================
# BASE MODEL
# ============================================================

class Base(DeclarativeBase):
    pass


# ============================================================
# USER MODEL
# ============================================================

class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    email: Mapped[str] = mapped_column(
        String(150),
        nullable=False
    )

    tasks: Mapped[list["Task"]] = relationship(
        back_populates="user"
    )

    projects: Mapped[list["Project"]] = relationship(
        back_populates="user"
    )


# ============================================================
# PROJECT MODEL
# ============================================================

class Project(Base):
    __tablename__ = "projects"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    name: Mapped[str] = mapped_column(
        String(150),
        nullable=False
    )

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id"),
        nullable=False,
        index=True
    )

    user: Mapped["User"] = relationship(
        back_populates="projects"
    )

    tasks: Mapped[list["Task"]] = relationship(
        back_populates="project"
    )


# ============================================================
# TASK MODEL
# ============================================================

class Task(Base):
    __tablename__ = "tasks"

    __table_args__ = (
        Index(
            "ix_tasks_user_id_completed",
            "user_id",
            "completed"
        ),
    )

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    title: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    completed: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False
    )

    priority: Mapped[int] = mapped_column(
        Integer,
        default=3,
        nullable=False
    )

    description: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True
    )

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id"),
        nullable=False,
        index=True
    )

    due_date: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True
    )

    project_id: Mapped[int | None] = mapped_column(
        ForeignKey("projects.id"),
        nullable=True,
        index=True
    )

    user: Mapped["User"] = relationship(
        back_populates="tasks"
    )

    project: Mapped["Project | None"] = relationship(
        back_populates="tasks"
    )


# ============================================================
# CREATE TEST DATA
# ============================================================

michael = User(
    name="Michael",
    email="michael@gmail.com"
)


backend_engineering = Project(
    name="Backend Engineering",
    user=michael
)


api_project = Project(
    name="API Project",
    user=michael
)


task1 = Task(
    title="Study SQLAlchemy",
    priority=5,
    user=michael,
    project=backend_engineering
)


task2 = Task(
    title="Practice Alembic",
    priority=4,
    user=michael,
    project=backend_engineering
)


task3 = Task(
    title="Build Authentication",
    priority=5,
    user=michael,
    project=api_project
)


task4 = Task(
    title="Add Rate Limiting",
    priority=4,
    user=michael,
    project=api_project
)


# ============================================================
# DATABASE SESSION
# ============================================================

with Session(engine) as session:

    # --------------------------------------------------------
    # SAVE DATA
    # --------------------------------------------------------

    session.add(michael)
    session.commit()

    # Michael now has an ID generated by the database.
    print(f"Michael ID: {michael.id}")


    # ========================================================
    # QUERY 1
    # Print all Projects belonging to Michael
    # ========================================================

    print("\n--- Michael's Projects ---")

    statement = (
        select(Project)
        .where(Project.user_id == michael.id)
    )

    projects = session.scalars(statement).all()

    for project in projects:
        print(f"Project: {project.name}")


    # ========================================================
    # QUERY 2
    # Print all Tasks belonging to Backend Engineering
    # using relationship traversal
    # ========================================================

    print("\n--- Backend Engineering Tasks ---")

    for task in backend_engineering.tasks:
        print(
            f"Task: {task.title} | "
            f"Project: {task.project.name}"
        )


    # ========================================================
    # QUERY 3
    # Query Backend Engineering Tasks using project_id
    # ========================================================

    print("\n--- Backend Engineering Tasks Using project_id ---")

    statement = (
        select(Task)
        .where(
            Task.project_id == backend_engineering.id
        )
    )

    tasks = session.scalars(statement).all()

    for task in tasks:
        print(
            f"Task: {task.title} | "
            f"Project ID: {task.project_id}"
        )


    # ========================================================
    # QUERY 4
    # Query API Project Tasks using an explicit JOIN
    # ========================================================

    print("\n--- API Project Tasks Using JOIN ---")

    statement = (
        select(Task)
        .join(Task.project)
        .where(Project.name == "API Project")
    )

    tasks = session.scalars(statement).all()

    for task in tasks:
        print(
            f"Task: {task.title} | "
            f"Project: {task.project.name}"
        )


    # ========================================================
    # QUERY 5
    # Query Tasks belonging to Projects owned by Michael
    #
    # Relationship path:
    #
    # Task -> Project -> User
    # ========================================================

    print("\n--- Tasks From Projects Owned by Michael ---")

    statement = (
        select(Task)
        .join(Task.project)
        .join(Project.user)
        .where(User.name == "Michael")
    )

    tasks = session.scalars(statement).all()

    for task in tasks:
        print(
            f"Task: {task.title} | "
            f"Project: {task.project.name} | "
            f"Owner: {task.project.user.name}"
        )


# ============================================================
# DAY 43 Q&A
# ============================================================


# 1. What type of relationship exists between
#    User and Project?
#
# One-to-many.
#
# One User can own many Projects, while each Project belongs
# to one User.
#
# User.projects -> collection of Project objects
# Project.user  -> one User object


# 2. What type of relationship exists between
#    Project and Task?
#
# One-to-many.
#
# One Project can contain many Tasks, while each Task can
# belong to one Project.
#
# Project.tasks -> collection of Task objects
# Task.project  -> one Project object


# 3. What does projects.user_id reference?
#
# projects.user_id references users.id.
#
# It stores the primary-key ID of the User who owns
# the Project.
#
# projects.user_id -> users.id


# 4. What does tasks.project_id reference?
#
# tasks.project_id references projects.id.
#
# It stores the primary-key ID of the Project that
# the Task belongs to.
#
# tasks.project_id -> projects.id


# 5. Why are user_id and project_id database columns,
#    while user and project are ORM relationships?
#
# user_id and project_id are actual database columns.
#
# They store foreign-key values such as:
#
# user_id = 1
# project_id = 5
#
# user and project are ORM relationships.
#
# They allow Python code to navigate directly to related
# ORM objects.
#
# For example:
#
# task.user
#
# returns a User ORM object.
#
# task.project
#
# returns a Project ORM object.
#
# Therefore:
#
# user_id / project_id -> database foreign-key values
# user / project       -> Python ORM object navigation


# 6. Why did we initially make project_id nullable?
#
# Because Tasks may already exist in the database before
# the project_id column is introduced.
#
# Those existing rows do not have a Project yet.
#
# If project_id were immediately NOT NULL, existing rows
# could violate the new constraint.
#
# Making it nullable allows the schema change to be introduced
# safely while preserving existing data.
#
# A later migration could assign Projects to old Tasks before
# making the column required.


# 7. Why is Project.user_id a reasonable index candidate?
#
# Because the application will frequently perform queries such as:
#
# WHERE user_id = ?
#
# For example:
#
# "Give me all Projects belonging to Michael."
#
# An index on projects.user_id can potentially make this
# query more efficient.


# 8. Why is Task.project_id a reasonable index candidate?
#
# Because retrieving all Tasks belonging to a particular
# Project is expected to be a common operation.
#
# For example:
#
# WHERE project_id = ?
#
# An index on project_id can potentially make this lookup
# more efficient.


# 9. What does project.tasks return conceptually?
#
# It returns the collection of Task ORM objects associated
# with that Project.
#
# For example:
#
# backend_engineering.tasks
#
# could conceptually contain:
#
# Study SQLAlchemy
# Practice Alembic


# 10. What does task.project return conceptually?
#
# It returns the single Project ORM object associated
# with the Task.
#
# Therefore:
#
# project.tasks -> collection of Tasks
#
# task.project -> one Project


# 11. What is the difference between:
#
#     project.tasks
#
# and:
#
#     select(Task).where(Task.project_id == project.id)
#
# project.tasks uses ORM relationship traversal.
#
# It navigates from an existing Project ORM object to its
# related Task objects.
#
# select(Task).where(...) explicitly constructs a database
# query that asks the database to retrieve matching Tasks.
#
# Therefore:
#
# project.tasks
# -> relationship traversal
#
# select(Task).where(...)
# -> explicit database query


# 12. How can SQLAlchemy know what value should eventually
#     be stored in project_id when I create a Task using:
#
#     project=backend_project
#
# SQLAlchemy knows because the ORM relationship and foreign
# key have been configured together.
#
# Task.project is connected to Project.tasks through:
#
# back_populates
#
# and:
#
# tasks.project_id
#
# references:
#
# projects.id
#
# Therefore, when:
#
# project=backend_project
#
# is assigned, SQLAlchemy understands that project_id should
# reference the primary key of backend_project when the objects
# are persisted.


# 13. What does this JOIN mean?
#
#     select(Task)
#         .join(Task.project)
#         .where(Project.name == "Backend Learning")
#
# It means:
#
# Retrieve Task records whose related Project has the name
# "Backend Learning".
#
# The relationship path is:
#
# Task
#   |
#   v
# Task.project
#   |
#   v
# Project
#
# SQLAlchemy joins Tasks to their Projects and then filters
# the results using Project.name.


# 14. What relationship path is followed by:
#
#     Task -> Project -> User
#
# At the ORM level:
#
# Task.project
#     |
#     v
# Project.user
#     |
#     v
# User
#
# At the database level:
#
# tasks.project_id
#     |
#     v
# projects.id
#
# projects.user_id
#     |
#     v
# users.id
#
# This allows the application to move from a Task to the
# Project it belongs to and then to the User who owns
# that Project.


# 15. Why could keeping both Task.user_id and
#     Task.project_id create inconsistent ownership data?
#
# Because Task.user_id provides one ownership path:
#
# Task -> User
#
# while project_id provides another:
#
# Task -> Project -> User
#
# These two paths could disagree.
#
# For example:
#
# Michael.id = 1
# Sarah.id = 2
#
# Project 5 belongs to Sarah:
#
# Project.user_id = 2
#
# But a Task could accidentally contain:
#
# Task.user_id = 1
# Task.project_id = 5
#
# Now:
#
# task.user
# -> Michael
#
# but:
#
# task.project.user
# -> Sarah
#
# Both foreign keys are individually valid because User 1
# exists and Project 5 exists.
#
# Ordinary foreign keys do not automatically know the business
# rule that both ownership paths should refer to the same User.
#
# If every Task must belong to a Project and every Project
# belongs to exactly one User, Task.user_id may be redundant.
#
# Ownership could instead be derived through:
#
# Task
#   |
#   v
# Project
#   |
#   v
# User
#
# This gives the database one clear source of truth for
# Task ownership.
#
# However, if Task.user_id represented something different,
# such as the User assigned to perform the Task, then keeping
# both relationships could make sense.
#
# In that case, the field should have a clearer name such as:
#
# assignee_id
#
# so that:
#
# Project.user_id -> Project owner
# Task.assignee_id -> User assigned to Task
#
# This avoids ambiguous ownership relationships.


# ============================================================
# FINAL OWNERSHIP CHALLENGE
# ============================================================

# Suppose:
#
# Michael.id = 1
# Sarah.id = 2
#
# and the Backend Project belongs to Sarah:
#
# Project.user_id = 2
#
# but someone creates:
#
# Task.user_id = 1
# Task.project_id = Backend Project
#
#
# What is wrong?
#
# The Task now has conflicting ownership information.
#
# Task.user says Michael owns or is associated with the Task,
# while Task.project.user says Sarah owns the Project containing
# the Task.


# Would ordinary foreign keys automatically prevent it?
#
# No.
#
# The foreign keys only verify that the referenced records exist.
#
# Task.user_id = 1 is valid because User 1 exists.
#
# Task.project_id = 5 is valid because Project 5 exists.
#
# They do not automatically enforce the business rule that the
# Task's User must be the same User who owns its Project.


# How could the design avoid this?
#
# One solution is to remove Task.user_id if Task ownership can
# always be determined through the Project.
#
# Then:
#
# Task -> Project -> User
#
# becomes the single source of truth.
#
# Another possibility is application-level validation that checks
# that Task.user_id matches Task.project.user_id.
#
# More advanced database constraints could also be considered
# depending on the database design and requirements.


# Do we necessarily need Task.user_id if every Task belongs
# to a Project and every Project belongs to exactly one User?
#
# No.
#
# If Task.user_id only represents ownership, it is redundant
# because the owner can already be determined through:
#
# Task.project.user
#
# Removing the duplicated ownership field can make the schema
# simpler and prevent contradictory ownership data.
#
# If the direct User relationship has a different business
# meaning, such as Task assignee, then it can remain but should
# be clearly named to represent that different purpose.