from sqlalchemy import (
    Boolean,
    ForeignKey,
    Integer,
    String,
    create_engine
)

from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship
)


DATABASE_URL = "sqlite:///./day40.db"

engine = create_engine(DATABASE_URL)


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    email: Mapped[str] = mapped_column(
        String(150),
        nullable=False
    )

    tasks: Mapped[list["Task"]] = relationship(
        back_populates="user"
    )


class Task(Base):
    __tablename__ = "tasks"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    title: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    completed: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False
    )

    priority: Mapped[int] = mapped_column(
        Integer,
        default=3,
        nullable=False
    )

    description: Mapped[str | None] = mapped_column(
    String(500),
    nullable=True
)

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id"),
        nullable=False
    )

    due_date: Mapped[str | None] = mapped_column(
    String(20),
    nullable=True
)

    user: Mapped["User"] = relationship(
        back_populates="tasks"
    )


# Add column safely
#       ↓
# Backfill existing records
#       ↓
# Enforce NOT NULL
# why each steps are necessary cause we need to make sure that the previous data in the table doesn't throw an error when we are using not null for a newly created column for tasks


# 1. What does revision represent in an Alembic migration?
# revision is the unique identifier for that migration file.


# 2. What does down_revision represent?
# down_revision identifies the migration revision that comes
# immediately before the current migration.


# 3. Why does Alembic need migration revisions
#    to form a dependency chain?
# Alembic needs a dependency chain so it knows the correct
# order in which schema changes must be applied or reversed.
# Some migrations depend on structures created by earlier migrations.


# 4. Why is adding a nullable column usually easier
#    than adding a non-nullable column to a populated table?
# A nullable column allows existing rows to temporarily contain NULL.
# A non-nullable column requires every existing row to immediately
# have a valid value.


# 5. What could happen if I add a NOT NULL column
#    to a table containing existing rows without
#    providing values for those rows?
# The migration may fail because the existing rows would violate
# the NOT NULL constraint.


# 6. What is a backfill?
# A backfill is the process of populating existing rows with
# values for a newly introduced column or corrected data.


# 7. Why might we add a column as nullable first,
#    backfill it, and only then make it NOT NULL?
# First, nullable=True allows the column to be added safely.
# Then existing rows are backfilled with valid values.
# Once every row contains a value, NOT NULL can be enforced safely.


# 8. What does alembic downgrade -1 do?
# It moves the database back by one migration revision.


# 9. Does a successful downgrade guarantee that no
#    data will be lost? Explain.
# No. A downgrade may remove columns, tables, or other structures
# containing data. Alembic tracks schema migrations, but it does not
# automatically preserve all application data.


# 10. What is the difference between a SQLAlchemy
#     default and a database server_default?
# default is usually applied by SQLAlchemy on the Python/application
# side when inserting a row.
#
# server_default is defined at the database level, so the database
# itself supplies the default value.


# 11. Why should upgrade() and downgrade() always
#     be inspected before applying a migration?
# Autogenerated migrations can be incomplete, incorrect, or unsafe.
# They should be checked to confirm they perform the intended schema
# change and do not unexpectedly destroy data.


# 12. If the current migration chain is:
#
#     A -> B -> C
#
#     and C is head, what does B represent relative
#     to C?
# B is the previous migration revision immediately before C.
# C's down_revision would point to B.

# 1. What problem do database migrations solve?
# Database migrations allow us to change an existing database schema
# over time without deleting and recreating the entire database.
# They can add, remove, or modify tables, columns, indexes, and
# constraints while preserving existing data where possible.


# 2. Why is Base.metadata.create_all() not enough
#    for production schema evolution?
# create_all() mainly creates tables that do not already exist.
# It does not properly track or manage changes to existing schemas,
# so it is not a replacement for migrations.


# 3. What is Alembic?
# Alembic is a database migration tool commonly used with SQLAlchemy.
# It creates, tracks, applies, and reverses versioned database
# schema changes.


# 4. What is Base.metadata used for by Alembic?
# Base.metadata contains SQLAlchemy's schema information such as
# tables, columns, foreign keys, and constraints.
# Alembic can compare this metadata with the current database schema.


# 5. What does target_metadata = Base.metadata do?
# It gives Alembic access to the SQLAlchemy model metadata so
# autogenerate can compare the ORM schema with the actual database.


# 6. What is the difference between:
#    alembic revision --autogenerate
#    and
#    alembic upgrade head?
#
# revision --autogenerate compares the database schema with
# the SQLAlchemy metadata and generates a migration file.
# 
# upgrade head applies the migrations to the actual database
# and moves it to the latest migration version.


# 7. What does upgrade() represent?
# upgrade() contains the operations required to move the
# database schema forward to the newer migration version.


# 8. What does downgrade() represent?
# downgrade() contains the operations required to reverse
# the migration and return the database to the previous version.


# 9. What does "head" mean in Alembic?
# head means the latest migration revision in the current
# Alembic migration chain.


# 10. If I add a new field to my SQLAlchemy model,
#     does that automatically add the column to an
#     existing database? Explain.
# No. Changing the SQLAlchemy model only changes the Python
# model definition. The database must be updated by generating
# a migration and applying it with Alembic.


# 11. Why should generated migrations be inspected
#     before applying them?
# Autogenerated migrations may be incomplete, incorrect, or unsafe.
# They should be reviewed to make sure the generated operations
# match the intended database schema change.


# 12. What does alembic downgrade -1 do?
# It moves the database back by one migration revision by
# running the downgrade() function of the current migration.