from sqlalchemy import (
    Boolean,
    ForeignKey,
    Integer,
    String,
    create_engine,
    Index,
    select,
)

from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
    Session,
    selectinload,
    joinedload,
)


DATABASE_URL = "sqlite:///./day40.db"

# echo=True allows us to see the SQL generated by SQLAlchemy.
# This is especially useful today because we want to observe
# the N+1 problem and compare loading strategies.
engine = create_engine(DATABASE_URL, echo=True)


# ============================================================
# BASE MODEL
# ============================================================

class Base(DeclarativeBase):
    pass


# ============================================================
# USER MODEL
# ============================================================

class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    email: Mapped[str] = mapped_column(
        String(150),
        nullable=False
    )

    tasks: Mapped[list["Task"]] = relationship(
        back_populates="user"
    )

    projects: Mapped[list["Project"]] = relationship(
        back_populates="user"
    )


# ============================================================
# PROJECT MODEL
# ============================================================

class Project(Base):
    __tablename__ = "projects"

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    name: Mapped[str] = mapped_column(
        String(150),
        nullable=False
    )

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id"),
        nullable=False,
        index=True
    )

    user: Mapped["User"] = relationship(
        back_populates="projects"
    )

    tasks: Mapped[list["Task"]] = relationship(
        back_populates="project"
    )


# ============================================================
# TASK MODEL
# ============================================================

class Task(Base):
    __tablename__ = "tasks"

    __table_args__ = (
        Index(
            "ix_tasks_user_id_completed",
            "user_id",
            "completed"
        ),
    )

    id: Mapped[int] = mapped_column(
        primary_key=True
    )

    title: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    completed: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False
    )

    priority: Mapped[int] = mapped_column(
        Integer,
        default=3,
        nullable=False
    )

    description: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True
    )

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id"),
        nullable=False,
        index=True
    )

    due_date: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True
    )

    project_id: Mapped[int | None] = mapped_column(
        ForeignKey("projects.id"),
        nullable=True,
        index=True
    )

    user: Mapped["User"] = relationship(
        back_populates="tasks"
    )

    project: Mapped["Project | None"] = relationship(
        back_populates="tasks"
    )


# ============================================================
# PART A - LAZY LOADING / N+1 EXPERIMENT
# ============================================================

print("\n========== PART A: LAZY LOADING ==========\n")

with Session(engine) as session:

    statement = select(Project)

    projects = session.scalars(statement).all()

    for project in projects:
        print(f"Project: {project.name}")

        # Because Project.tasks is being accessed here,
        # SQLAlchemy may execute another query to retrieve
        # the tasks for this particular project.
        for task in project.tasks:
            print(f"    Task: {task.title}")


# ============================================================
# PART B - SELECTINLOAD
# ============================================================

print("\n========== PART B: SELECTINLOAD ==========\n")

with Session(engine) as session:

    statement = (
        select(Project)
        .options(
            selectinload(Project.tasks)
        )
    )

    projects = session.scalars(statement).all()

    for project in projects:
        print(f"Project: {project.name}")

        # The tasks were eagerly loaded using selectinload,
        # so accessing project.tasks should not cause one
        # separate query for every project.
        for task in project.tasks:
            print(f"    Task: {task.title}")


# ============================================================
# PART C - JOINEDLOAD
# ============================================================

print("\n========== PART C: JOINEDLOAD ==========\n")

with Session(engine) as session:

    statement = (
        select(Task)
        .options(
            joinedload(Task.project)
        )
    )

    tasks = session.scalars(statement).all()

    for task in tasks:

        # project_id is nullable, so some old tasks may not
        # belong to a project.
        if task.project is not None:
            project_name = task.project.name
        else:
            project_name = "No Project"

        print(
            f"Task: {task.title} | "
            f"Project: {project_name}"
        )


# ============================================================
# PART D - MULTI-LEVEL EAGER LOADING
# ============================================================

print("\n========== PART D: MULTI-LEVEL LOADING ==========\n")

with Session(engine) as session:

    statement = (
        select(User)
        .options(
            selectinload(User.projects)
            .selectinload(Project.tasks)
        )
        .where(User.name == "Michael")
    )

    users = session.scalars(statement).all()

    for user in users:
        print(f"\nUser: {user.name}")

        for project in user.projects:
            print(f"Project: {project.name}")

            for task in project.tasks:
                print(f"    Task: {task.title}")


# ============================================================
# FINAL CHALLENGE
# ============================================================

# Imagine there are:
#
# 1,000 Projects
# 20 Tasks per Project
#
#
# A. With an N+1 pattern, approximately how many queries
#    could occur?
#
# Answer:
# Approximately 1,001 queries.
#
# 1 query retrieves the 1,000 Projects.
# Then potentially 1 additional query retrieves Tasks
# for each Project.
#
# 1 + 1,000 = 1,001 queries.
#
#
# B. With selectinload(Project.tasks), what is the basic
#    query strategy?
#
# Answer:
# SQLAlchemy first retrieves the Projects and then retrieves
# their related Tasks in a separate query using the Project
# IDs, commonly with an IN (...) condition.
#
# Conceptually:
#
# Query 1 -> retrieve Projects
# Query 2 -> retrieve Tasks whose project_id belongs to
#            those Projects
#
# For very large parent sets, SQLAlchemy may batch the
# secondary SELECTs rather than literally using only one
# Task query.
#
#
# C. Why might blindly JOINing Projects and Tasks also
#    have costs?
#
# Answer:
# A Project with 20 Tasks can cause the Project information
# to appear repeatedly across multiple result rows.
#
# For example:
#
# Project A + Task 1
# Project A + Task 2
# Project A + Task 3
# ...
#
# This can increase the amount of data returned and processed.
# Therefore, JOINing everything is not automatically the
# fastest solution.
#
#
# D. Should we decide the fastest strategy purely from theory?
#
# Answer:
# No.
#
# We should inspect the generated SQL and benchmark realistic
# workloads because performance depends on factors such as
# the amount of data, relationship cardinality, indexes,
# database engine, query pattern and application workload.


# ============================================================
# DAY 44 Q&A
# ============================================================

# 1. What is lazy loading?
#
# Lazy loading means related data is not necessarily loaded
# when the original object is retrieved.
#
# Instead, SQLAlchemy loads the related data when the
# relationship attribute is accessed.
#
# For example:
#
# project.tasks
#
# may cause SQLAlchemy to retrieve that Project's Tasks when
# the attribute is accessed.


# 2. What is the N+1 query problem?
#
# The N+1 problem happens when an application executes one
# query to retrieve a collection of parent objects and then
# executes additional queries for each parent to retrieve
# related data.
#
# For example:
#
# 1 query -> retrieve Projects
#
# +
#
# N queries -> retrieve Tasks for N Projects
#
# This can create a large number of unnecessary database
# queries.


# 3. If one query retrieves 50 Projects and lazy loading
#    causes one additional Task query per Project,
#    approximately how many total queries could occur?
#
# Answer:
#
# 51 queries.
#
# 1 Project query
#
# +
#
# 50 Task queries
#
# =
#
# 51 queries.


# 4. What does selectinload(Project.tasks) help us avoid?
#
# It helps avoid performing one separate Task query for
# every Project when we already know that the Tasks will
# be needed.
#
# SQLAlchemy can retrieve the Projects first and then load
# their related Tasks using the Project IDs in additional
# batched query/queryies.


# 5. What is the basic difference between selectinload()
#    and joinedload()?
#
# selectinload() normally loads the parent objects first and
# then retrieves related objects using one or more additional
# SELECT queries.
#
# joinedload() loads the relationship using a JOIN as part
# of the eager-loading operation.
#
# A useful starting mental model is:
#
# Collections such as:
#
# Project.tasks
#
# -> selectinload() is often useful.
#
# Single related objects such as:
#
# Task.project
#
# -> joinedload() can be useful.
#
# This is not an absolute rule. The best strategy depends
# on the actual query and workload.


# 6. Why is this wrong?
#
# for project in task.project:
#
# Answer:
#
# Because task.project represents one Project object,
# not a collection of Projects.
#
# Task.project is a many-to-one relationship.
#
# Therefore we can access:
#
# task.project.name
#
# instead of trying to loop over task.project.
#
# In our model project_id is nullable, so we should also
# consider the possibility that task.project is None.


# 7. What is the difference between join() and joinedload()?
#
# join() is primarily used as part of the query itself.
#
# For example, we may JOIN Project because we want to filter
# Tasks based on Project information:
#
# select(Task)
#     .join(Task.project)
#     .where(Project.name == "API Project")
#
# joinedload(), on the other hand, is a relationship-loading
# strategy.
#
# It tells SQLAlchemy that we want a related object loaded
# eagerly because our Python code is going to use it.
#
# Mental model:
#
# join()
# -> query logic
#
# joinedload()
# -> relationship loading strategy


# 8. Why is this incorrect?
#
# for user in User:
#
# What should we iterate over instead?
#
# Answer:
#
# User is an ORM class.
#
# It represents the model/table structure. It is not the
# collection of User objects returned from the database.
#
# We first execute a query:
#
# users = session.scalars(
#     select(User)
# ).all()
#
# Then we iterate over:
#
# for user in users:
#     print(user.name)
#
# Mental model:
#
# User
# -> ORM class / blueprint
#
# user
# -> one User ORM object
#
# users
# -> collection of User ORM objects